import {useMemo,useState} from 'react';
import {Copy,Download,FlaskConical,Upload,Zap} from 'lucide-react';
import {GlassCard} from '../../components/ui/GlassCard';
import {GlassButton} from '../../components/ui/GlassButton';
import {decodeOptiFrame,encodeOptiFrame,getOptiFrameCapacity,OPTIFRAME_SIZE} from '../../lib/optiframe';

export function OptiFrameLab(){
 const[text,setText]=useState('OptiCode experimental optical frame'),[seq,setSeq]=useState(0),[total,setTotal]=useState(1),[image,setImage]=useState(''),[decoded,setDecoded]=useState(''),[status,setStatus]=useState('Generate a frame to begin.');
 const capacity=useMemo(()=>getOptiFrameCapacity(),[]);
 function generate(){try{const payload=new TextEncoder().encode(text);const out=encodeOptiFrame(payload,seq,total);setImage(out.canvas.toDataURL('image/png'));setDecoded('');setStatus('Encoded with 4 luminance levels, 2-bit symbols and CRC-32.');}catch(e){setStatus(e instanceof Error?e.message:'Unable to encode frame.');}}
 function load(file?:File){if(!file)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{try{const out=decodeOptiFrame(img);if(!out)throw new Error('Rejected: invalid frame or CRC mismatch.');setDecoded(new TextDecoder().decode(out.payload));setStatus('Decoded successfully; CRC-32 verified.');}catch(e){setStatus(e instanceof Error?e.message:'Unable to decode frame.');}finally{URL.revokeObjectURL(url);}};img.src=url;}
 function save(){if(!image)return;const a=document.createElement('a');a.href=image;a.download='optiframe.png';a.click();}
 async function copy(){if(decoded&&navigator.clipboard)await navigator.clipboard.writeText(decoded);}
 return <section className="mx-auto max-w-6xl py-8 sm:py-12"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">Phase 2 · Experimental</p><h1 className="mt-2 text-4xl font-black text-[var(--text)] sm:text-6xl">OptiFrame Lab</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-[var(--text-muted)]">A custom optical symbol experiment beyond QR: 128×128 modules, four luminance levels, 2 bits per module, explicit metadata and CRC-32. It remains separate from production QR transport.</p>
 <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_1.05fr]"><GlassCard><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-400/10 text-violet-300"><FlaskConical size={18}/></span><div><p className="text-xs font-bold text-[var(--text)]">Custom symbol protocol</p><p className="text-[10px] uppercase tracking-[.14em] text-[var(--text-muted)]">{capacity} payload bytes / frame</p></div></div>
 <textarea value={text} onChange={e=>setText(e.target.value)} className="mt-5 min-h-36 w-full rounded-[22px] border border-[var(--border)] bg-[var(--bg-soft)] p-4 text-sm text-[var(--text)] outline-none"/>
 <div className="mt-4 grid grid-cols-2 gap-3"><label className="rounded-2xl border border-[var(--border)] bg-[var(--bg-soft)] p-3"><span className="text-[10px] text-[var(--text-muted)]">Sequence</span><input type="number" min="0" max="65535" value={seq} onChange={e=>setSeq(Number(e.target.value)||0)} className="mt-1 w-full bg-transparent text-[var(--text)] outline-none"/></label><label className="rounded-2xl border border-[var(--border)] bg-[var(--bg-soft)] p-3"><span className="text-[10px] text-[var(--text-muted)]">Total</span><input type="number" min="1" max="65535" value={total} onChange={e=>setTotal(Math.max(1,Number(e.target.value)||1))} className="mt-1 w-full bg-transparent text-[var(--text)] outline-none"/></label></div>
 <div className="mt-4 flex flex-wrap gap-2"><GlassButton onClick={generate}><Zap size={14}/> Generate OptiFrame</GlassButton><label className="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-elevated)] px-4 py-2 text-sm font-bold text-[var(--text)]"><Upload size={14}/> Decode image<input type="file" accept="image/*" className="hidden" onChange={e=>load(e.target.files?.[0])}/></label></div>
 <div className="mt-4 rounded-2xl border border-[var(--border)] bg-[var(--bg-soft)] p-4"><p className="text-xs font-bold text-[var(--text)]">Status</p><p className="mt-1 text-xs text-[var(--text-muted)]">{status}</p></div>
 {decoded&&<div className="mt-4 rounded-2xl border border-emerald-300/20 bg-emerald-300/10 p-4"><p className="text-[10px] font-black uppercase tracking-[.14em] text-emerald-300">Verified payload</p><p className="mt-2 break-words text-sm text-[var(--text)]">{decoded}</p><button onClick={()=>void copy()} className="mt-3 inline-flex items-center gap-2 rounded-full border border-[var(--border)] px-3 py-2 text-xs font-bold text-[var(--text)]"><Copy size={13}/> Copy</button></div>}</GlassCard>
 <GlassCard><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-[var(--text)]">Optical surface</p><p className="mt-1 text-[10px] uppercase tracking-[.14em] text-[var(--text-muted)]">{OPTIFRAME_SIZE}×{OPTIFRAME_SIZE} · 4 levels</p></div>{image&&<button onClick={save} className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] px-3 py-2 text-xs font-bold text-[var(--text)]"><Download size={13}/> Save</button>}</div><div className="mt-5 grid place-items-center rounded-[26px] bg-white p-4">{image?<img src={image} alt="OptiFrame custom optical code" className="block aspect-square w-full max-w-[560px] [image-rendering:pixelated]"/>:<div className="aspect-square w-full max-w-[560px]"/>}</div></GlassCard></div>
 <div className="mt-5 rounded-[26px] border border-amber-300/20 bg-amber-300/10 p-5"><p className="text-sm font-black text-[var(--text)]">Lab status</p><p className="mt-1 text-xs leading-6 text-[var(--text-muted)]">The decoder is intentionally strict and axis-aligned. It validates image files but is not yet a perspective-corrected live camera decoder. That is the next OptiFrame milestone.</p></div></section>;
}
